### ISSUE TITLE
Could not connect to discord

### ISSUE THREAD

**Issue by realyukii** [piotro888/vscode-disocrd-rich-presence#10]
### Bug description
Could not connect to discord
![image](https://github.com/piotro888/vscode-discord-rich-presence/assets/126035476/3ded8b72-b2fe-429e-be26-3d4e30429ea3)

### Steps to reproduce
- install vsix through vscode
- reload
- error appears

### Expected behaviour
No errors, and expect to be working properly :)

### Actual behaviour
Error occurs on notification popup vscode

### Configuration
- OS: WSL Ubuntu on host Windows 11
- Extension version: 2.2.0

### Additional info
Discord is already running, and VSCode has been added to registered games.

**Comment by frankiensteinne** [comment]
encountered same issue. reinstalled both discord and vscode, refreshed both newly installed apps and worked.

**Comment by awariac** [comment]
@frankiensteinne thanks for feedback!

@Reyuki-san please make sure that you have both Discord and VSCode installed as normal packages, and not ex. from `snap`.
You can verify this with `snap list`, and probably `whereis discord`, `whereis code` commands. It is a known issue that packages from `snap` can't communicate because of used sandboxing. Or are the both apps on the same host OS (the same issue)?

**Comment by realyukii** [comment]
I use windows btw
